server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=X-Gateway, api-gateway
      #      globalcors:
      #        '[/**]':
      #          allowedOrigins:
      #            - "http://localhost:3000"
      #            - "http://localhost:3001"
      #          allowedMethods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
      #          allowedHeaders: ["*"]
      #          exposedHeaders: [Location]
      #          allowCredentials: true
      routes:
        - id: hotel-management-service
          uri: lb://hotel-management-service
          predicates:
            - Path=/hotels/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
          filters:
            - RemoveRequestHeader=Cookie
            - StripPrefix=1
    discovery:
      locator:
        enabled: false
        lower-case-service-id: true

    httpclient:
      connect-timeout: 3000
      response-timeout: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret: hAIt9N0vnfIYlM1YdRlysMFWJY0LxASdWfWCiJdz73n7oZogbA5ZQpZs3ZkY8p3Il1k9n5cY4poPqV2h7CwJdA==
    algorithm: HS256

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized

  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces

springdoc:
  swagger-ui:
    urls:
      - name: booking-service
        url: /bookings/v3/api-docs
      - name: hotel-management-service
        url: /hotels/v3/api-docs

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
    org.springframework.security: INFO
